### ISSUE TITLE
qt5: Error class QTextBrowser’ has no member named ‘setMarkdown

### ISSUE THREAD

**Issue by rwire1234** [DegateCommunity/Degate#14]
**Describe the bug**
A clear and concise description of what the bug I am trying to build a code from github but it gives error when the run the command sudo make. Please help. Also my qmake --version is

Using Qt version 5.14.2 in /opt/qt514/lib```

    AboutDialog.cc
/home/admin/delegate/Degate/src/GUI/Dialog/AboutDialog.cc: In constructor ‘degate::AboutDialog::AboutDialog(QWidget*)’:
/home/admin/delegate/Degate/src/GUI/Dialog/AboutDialog.cc:92:19: error: ‘class QTextBrowser’ has no member named ‘setMarkdown’
   92 |         changelog.setMarkdown(in_changelog.readAll());
      |                   ^~~~~~~~~~~
make[2]: *** [CMakeFiles/DegateCore.dir/build.make:3419: CMakeFiles/DegateCore.dir/src/GUI/Dialog/AboutDialog.cc.o] Error 1
make[2]: Leaving directory '/home/admin/delegate/Degate/build'
make[1]: *** [CMakeFiles/Makefile2:132: CMakeFiles/DegateCore.dir/all] Error 2
make[1]: Leaving directory '/home/admin/delegate/Degate/build'
make: *** [Makefile:133: all] Error 2

**Comment by DorianBDev** [comment]
Linked thread: https://stackoverflow.com/questions/73005956/qt5-error-class-qtextbrowser-has-no-member-named-setmarkdown. 

I'm going to investigate tonight.

**Comment by rwire1234** [comment]
Yes. It would be of great help. Looking forward to trying your tool. If you want can connect on a meeting too.

**Comment by DorianBDev** [comment]
I can confirm that the `setMarkdown` function was introduced in Qt 5.14.0. Regarding that, I think your Qt's installation is broken, since I just tested on a 5.14 install. One reason could be that you are using `sudo` to build Degate, and maybe it uses another version of Qt. Since the issue is surely coming from your installation, I cannot help you more. One solution could be to install the latest Qt5 version (5.15.5), an LTS, from the Qt installer (official): https://www.qt.io/download-open-source#section-2. Also, please read carefully the Degate's build instructions from the readme (available here: https://github.com/DegateCommunity/Degate#for-linux-debian-like).

If nothing work, you will need to provide more information:
- The result of `sudo qmake -v`,
- Full build logs,
- Which branch you are trying to build (master or develop),
- Your full OS version,
- The result of `uname -a`.

Finally, if you just want to try Degate, you can find prebuilt binaries here: https://github.com/DegateCommunity/Degate/releases/tag/v2.0.0 (latest release). If, like me, you are wondering about possible security issues regarding these prebuilt binaries, please check our security notice here: https://github.com/DegateCommunity/Degate/blob/develop/DOWNLOADS_SECURITY.md.

If you need anything else, don't hesitate :)

**Comment by DorianBDev** [comment]
You can also get latest binaries (from latest commits) here: https://github.com/DegateCommunity/Degate/actions/runs/2698967339. They are directly from the CI.

**Comment by DorianBDev** [comment]
I close this since there was no update for one month, feel free to reopen if needed.
