### ISSUE TITLE
Add project on Crowdin

### ISSUE THREAD

**Issue by XVilka** [DegateCommunity/Degate#17]
To make translations easier there is an amazing platform - [Crowdin](https://crowdin.com/).
It has GitHub and Qt Linguist integration out of the box. We (Cutter) happily use it:
- https://github.com/rizinorg/cutter-translations
- https://crowdin.com/project/cutter

**Comment by DorianBDev** [comment]
I just looked at Crowdin, seems amazing! Thanks for pointing that out, I'll integrate it in the next few days

**Comment by DorianBDev** [comment]
After looking deeper inside Crowdin's Github integration, I think I'll use the manual process (i.e., every so often exporting translation from Crowdin and merging into Degate's repository). I have concern about security (since Crowdin ask for too much access to Github accounts/repositories), for me the best choice would be to create a bot account & a side repository that only contains translations (the same way that Cutter does). For now I prefer to focus on the Qt6 migration and other PR merging before fully automating the process.

Here is the Crowdin Degate project, it should be ready to use: https://crowdin.com/project/degate. I'll update the README soon (not immediate since I'll also do a revamp of the project presentation, not up to date).

**Comment by DorianBDev** [comment]
Note that Degate is waiting to be accepted inside the Crowdin's Open-Source program (to avoid being word limited and other things).
