### ISSUE TITLE
Native theme collor dosent match the windows one

### ISSUE THREAD

**Issue by drone84** [DegateCommunity/Degate#32]
Right after a fresh install with the online installe the collor shem of the interface dosent match the one I have in windows. After cheking the preferance/apparance setting the theme mode is set as Native so the interface should be dark.
Manually sellecting dark work

1. Have windows in dark them
2. Install a fresh version with onlin install
2. look at the them collor

**Expected behavior**
the collor them od Degate should be dark

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Version: 23H2

**Comment by DorianBDev** [comment]
After checking the issue, I confirm the behavior. However, Qt doesn't support "native" dark theme for Windows. I can land a "fix" which will set dark theme by default on Windows if it detects dark theme at desktop level.

This will not land today since I need to rework the CI before being able to publish a new nightly version.

**Comment by DorianBDev** [comment]
After fixing the deploy CI I'll release a new nightly version (that'll feature a fix for this issue).

**Comment by DorianBDev** [comment]
A fix landed in the new [2.1.0-beta.2](https://github.com/DegateCommunity/Degate/releases/tag/v2.1.0-beta.2) pre-release. Pre-built binaries are available.
